### ISSUE TITLE
gifme doesn't work in Sketch 46.x

### ISSUE THREAD

**Issue by martimcflow** [kannonboy/sketch-gifme-plugin#4]
Hello!

I use Sketch, Version 46.2.

Downloaded latest Homebrew and installed latest gifme-plugin.
The gifme plugin shows up in sketch and I can select a mp4 file. After selecting the file, nothing happens. I also tried it with selecting a rectangle first.

**Comment by kannonboy** [comment]
Hi @martimcflow! There was a small change in one of the Sketch classes used by the plugin between Sketch 46.x & 47.x, which means we're currently only compatible with 47.x. 

Are you able to upgrade your Sketch to the latest version?

**Comment by ricochoi** [comment]
Hi

Is it still incompatible with sketch 48 or newer version?
Please help to solve that asap many thanks!

**Comment by kannonboy** [comment]
Hi @ricochoi!

Thanks for the nudge, version 0.2.1 supports Sketch 48.x: 

https://github.com/kannonboy/sketch-gifme-plugin/releases/tag/0.2.1

cheers,
Tim
